name: Laravel CI/CD (PHP 7.3)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: forge
          MYSQL_USER: root
          MYSQL_PASSWORD: root  # Tentukan password untuk user root
        ports:
          - 3306:3306
        options: |
          --health-cmd="mysqladmin ping --silent"  # Menambahkan perintah cek kesehatan MySQL
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'  # Versi PHP yang digunakan
        extensions: mbstring, pdo, pdo_mysql, xml  # Ekstensi yang dibutuhkan oleh Laravel
        coverage: none

    - name: Copy .env
      run: cp .env.example .env  # Salin .env dari .env.example

    - name: Set Environment Variables for Database
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env  # Menetapkan host ke 127.0.0.1 (alamat kontainer MySQL)
        echo "DB_PORT=3306" >> .env  # Port default MySQL
        echo "DB_DATABASE=forge" >> .env  # Nama database
        echo "DB_USERNAME=root" >> .env  # Username MySQL
        echo "DB_PASSWORD=root" >> .env  # Password untuk root

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist  # Install dependensi composer

    - name: Generate Application Key
      run: php artisan key:generate  # Generate application key

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        for i in {1..30}; do  # Tunggu hingga MySQL siap (30 detik maksimal)
          if mysqladmin ping -h 127.0.0.1 --silent; then
            echo "MySQL is up"
            break
          fi
          echo "Waiting for MySQL... ($i/30)"
          sleep 1
        done

    - name: Run Laravel Migrations
      run: php artisan migrate --force  # Jalankan migrasi database Laravel

    - name: Run Laravel Tests
      run: php artisan test  # Jalankan tes Laravel
