name: Laravel CI/CD (PHP 7.3)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: forge
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        extensions: mbstring, pdo, pdo_mysql, xml
        coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Set Environment Variables for Database
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=forge" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            echo "MySQL is up"
            break
          fi
          echo "Waiting for MySQL... ($i/30)"
          sleep 1
        done

    - name: Run Laravel Migrations
      run: php artisan migrate --force

    - name: Run Laravel Tests
      run: php artisan test
